version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: gaia
    env_file:
      - .env
volumes:
  postgres:
    name: gaia-db
