schema: "http://localhost:4000/graphql"
documents: "src/graphql/**/**.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - typescript-apollo-client-helpers
TSConfigFile: "tsconfig.json"
config:
  useTypeImports: true
  scalars:
    BigInt: number
    DateTime: Date
cacheDir: "../../generated/"
