schema: "http://localhost:4000/graphql"
documents: "src/graphql/**/**.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - typescript-apollo-client-helpers
TSConfigFile: "tsconfig.json"
cacheDir: __generated__
config:
  reactApolloVersion: 3
  useTypeImports: true
  scalars:
    BigInt: number
    DateTime: Date
