version: "3"

services:
  db:
    image: postgres
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_PASSWORD=prisma
